using System.Text;
using Verso.Abstractions;
using Verso.Export;

namespace Verso.Tests.Export;

[TestClass]
public sealed class NotebookHtmlExporterTests
{
    [TestMethod]
    public void Export_EmptyNotebook_ProducesValidHtmlStructure()
    {
        var html = ExportToString(null, Array.Empty<CellModel>(), null);

        Assert.IsTrue(html.Contains("<!DOCTYPE html>"));
        Assert.IsTrue(html.Contains("<html lang=\"en\">"));
        Assert.IsTrue(html.Contains("</html>"));
        Assert.IsTrue(html.Contains("<head>"));
        Assert.IsTrue(html.Contains("<body>"));
        Assert.IsTrue(html.Contains("Generated by Verso"));
    }

    [TestMethod]
    public void Export_WithTitle_TitleAppearsInTitleTagAndH1()
    {
        var html = ExportToString("My Notebook", Array.Empty<CellModel>(), null);

        Assert.IsTrue(html.Contains("<title>My Notebook</title>"));
        Assert.IsTrue(html.Contains("<h1>My Notebook</h1>"));
    }

    [TestMethod]
    public void Export_NullTitle_FallsBackToVersoNotebook()
    {
        var html = ExportToString(null, Array.Empty<CellModel>(), null);

        Assert.IsTrue(html.Contains("<title>Verso Notebook</title>"));
        Assert.IsTrue(html.Contains("<h1>Verso Notebook</h1>"));
    }

    [TestMethod]
    public void Export_MarkdownCell_RenderedViaMarkdig()
    {
        var cells = new[]
        {
            new CellModel { Type = "markdown", Source = "# Heading" }
        };

        var html = ExportToString(null, cells, null);

        // Markdig with UseAdvancedExtensions may add id attributes to headings
        Assert.IsTrue(html.Contains("<h1") && html.Contains("Heading</h1>"));
    }

    [TestMethod]
    public void Export_CodeCell_SourceInPreCode()
    {
        var cells = new[]
        {
            new CellModel { Type = "code", Language = "csharp", Source = "Console.WriteLine(\"hello\");" }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("<pre><code>"));
        Assert.IsTrue(html.Contains("Console.WriteLine(&quot;hello&quot;);"));
        Assert.IsTrue(html.Contains("csharp"));
    }

    [TestMethod]
    public void Export_TextPlainOutput_RenderedInOutputText()
    {
        var cells = new[]
        {
            new CellModel
            {
                Type = "code",
                Source = "x",
                Outputs = { new CellOutput("text/plain", "Hello World") }
            }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("verso-output--text"));
        Assert.IsTrue(html.Contains("Hello World"));
    }

    [TestMethod]
    public void Export_HtmlOutput_RawEmbed()
    {
        var cells = new[]
        {
            new CellModel
            {
                Type = "code",
                Source = "x",
                Outputs = { new CellOutput("text/html", "<div>Custom</div>") }
            }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("<div>Custom</div>"));
        Assert.IsTrue(html.Contains("verso-output--html"));
    }

    [TestMethod]
    public void Export_ErrorOutput_RenderedWithErrorClass()
    {
        var cells = new[]
        {
            new CellModel
            {
                Type = "code",
                Source = "x",
                Outputs = { new CellOutput("text/plain", "Something failed", IsError: true, ErrorName: "RuntimeError", ErrorStackTrace: "at Main()") }
            }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("verso-output--error"));
        Assert.IsTrue(html.Contains("RuntimeError"));
        Assert.IsTrue(html.Contains("Something failed"));
        Assert.IsTrue(html.Contains("at Main()"));
    }

    [TestMethod]
    public void Export_ImagePngOutput_RenderedAsDataUri()
    {
        var cells = new[]
        {
            new CellModel
            {
                Type = "code",
                Source = "x",
                Outputs = { new CellOutput("image/png", "iVBORw0KGgo=") }
            }
        };

        var html = ExportToString(null, cells, null);

        Assert.IsTrue(html.Contains("data:image/png;base64,iVBORw0KGgo="));
    }

    [TestMethod]
    public void Export_WithTheme_CssVariablesEmbedded()
    {
        var html = ExportToString(null, Array.Empty<CellModel>(), null);

        // Should contain CSS variables from default theme tokens
        Assert.IsTrue(html.Contains(":root {"));
        Assert.IsTrue(html.Contains("--verso-"));
    }

    [TestMethod]
    public void Export_TitleWithHtmlChars_IsEscaped()
    {
        var html = ExportToString("<script>alert('xss')</script>", Array.Empty<CellModel>(), null);

        Assert.IsFalse(html.Contains("<script>alert"));
        Assert.IsTrue(html.Contains("&lt;script&gt;"));
    }

    // ── Visibility-aware export tests ────────────────────────────────────

    [TestMethod]
    public void Export_NullOptions_AllCellsPresent()
    {
        var cells = new[]
        {
            new CellModel { Type = "code", Source = "cell1" },
            new CellModel { Type = "code", Source = "cell2" }
        };

        var html = ExportToString(null, cells, null, null);

        Assert.IsTrue(html.Contains("cell1"));
        Assert.IsTrue(html.Contains("cell2"));
    }

    [TestMethod]
    public void Export_PresentationLayout_HiddenCellSkipped()
    {
        var cell = new CellModel { Type = "code", Source = "secret-setup" };
        cell.Metadata["verso:visibility"] = new Dictionary<string, object>
        {
            ["presentation"] = "Hidden"
        };
        var cells = new CellModel[] { cell };

        var options = MakePresentationOptions();
        var html = ExportToString(null, cells, null, options);

        Assert.IsFalse(html.Contains("secret-setup"));
    }

    [TestMethod]
    public void Export_PresentationLayout_OutputOnlyCell_SourceAbsentOutputPresent()
    {
        var cell = new CellModel
        {
            Type = "code", Language = "sql", Source = "SELECT 1",
            Outputs = { new CellOutput("text/plain", "query-result-42") }
        };
        cell.Metadata["verso:visibility"] = new Dictionary<string, object>
        {
            ["presentation"] = "OutputOnly"
        };

        var options = MakePresentationOptions();
        var html = ExportToString(null, new[] { cell }, null, options);

        Assert.IsFalse(html.Contains("SELECT 1"));
        Assert.IsTrue(html.Contains("query-result-42"));
    }

    [TestMethod]
    public void Export_NotebookLayout_AllCellsVisible()
    {
        var cell = new CellModel { Type = "code", Source = "visible-cell" };
        cell.Metadata["verso:visibility"] = new Dictionary<string, object>
        {
            ["notebook"] = "Hidden"
        };

        var notebookOptions = new ExportOptions(
            "notebook",
            new HashSet<CellVisibilityState> { CellVisibilityState.Visible },
            new List<ICellRenderer> { new TestRenderer("code", CellVisibilityHint.Content) });

        var html = ExportToString(null, new[] { cell }, null, notebookOptions);

        // Notebook layout only supports Visible, so override is constrained to Visible
        Assert.IsTrue(html.Contains("visible-cell"));
    }

    [TestMethod]
    public void Export_PresentationLayout_InfrastructureHint_CellHidden()
    {
        var cell = new CellModel { Type = "parameters", Source = "param-setup" };

        var options = new ExportOptions(
            "presentation",
            new HashSet<CellVisibilityState> { CellVisibilityState.Visible, CellVisibilityState.Hidden, CellVisibilityState.OutputOnly },
            new List<ICellRenderer> { new TestRenderer("parameters", CellVisibilityHint.Infrastructure) });

        var html = ExportToString(null, new[] { cell }, null, options);

        Assert.IsFalse(html.Contains("param-setup"));
    }

    [TestMethod]
    public void Export_PresentationLayout_ExplicitVisibleOverride_InfrastructureCellPresent()
    {
        var cell = new CellModel { Type = "parameters", Source = "param-visible" };
        cell.Metadata["verso:visibility"] = new Dictionary<string, object>
        {
            ["presentation"] = "Visible"
        };

        var options = new ExportOptions(
            "presentation",
            new HashSet<CellVisibilityState> { CellVisibilityState.Visible, CellVisibilityState.Hidden, CellVisibilityState.OutputOnly },
            new List<ICellRenderer> { new TestRenderer("parameters", CellVisibilityHint.Infrastructure) });

        var html = ExportToString(null, new[] { cell }, null, options);

        Assert.IsTrue(html.Contains("param-visible"));
    }

    private static string ExportToString(string? title, IReadOnlyList<CellModel> cells, ITheme? theme)
    {
        var bytes = NotebookHtmlExporter.Export(title, cells, theme);
        return Encoding.UTF8.GetString(bytes);
    }

    private static string ExportToString(string? title, IReadOnlyList<CellModel> cells, ITheme? theme, ExportOptions? options)
    {
        var bytes = NotebookHtmlExporter.Export(title, cells, theme, options);
        return Encoding.UTF8.GetString(bytes);
    }

    private static ExportOptions MakePresentationOptions(CellVisibilityHint hint = CellVisibilityHint.Content)
        => new(
            "presentation",
            new HashSet<CellVisibilityState> { CellVisibilityState.Visible, CellVisibilityState.Hidden, CellVisibilityState.OutputOnly },
            new List<ICellRenderer> { new TestRenderer("code", hint) });

    private sealed class TestRenderer : ICellRenderer
    {
        private readonly CellVisibilityHint _hint;

        public TestRenderer(string cellTypeId, CellVisibilityHint hint)
        {
            CellTypeId = cellTypeId;
            _hint = hint;
        }

        public string CellTypeId { get; }
        CellVisibilityHint ICellRenderer.DefaultVisibility => _hint;
        public string DisplayName => CellTypeId;
        public string ExtensionId => "test." + CellTypeId;
        public string Name => CellTypeId;
        public string Version => "1.0.0";
        public string? Author => null;
        public string? Description => null;
        public Task OnLoadedAsync(IExtensionHostContext context) => Task.CompletedTask;
        public Task OnUnloadedAsync() => Task.CompletedTask;
        public Task<RenderResult> RenderInputAsync(string source, ICellRenderContext context) => throw new NotImplementedException();
        public Task<RenderResult> RenderOutputAsync(CellOutput output, ICellRenderContext context) => throw new NotImplementedException();
        public string? GetEditorLanguage() => null;
    }
}
