using System.Net;
using System.Text;
using Markdig;
using Verso.Abstractions;
using Verso.Extensions.Layouts;
using Verso.Extensions.Utilities;

namespace Verso.Export;

/// <summary>
/// Exports a notebook as a self-contained HTML document with embedded theme CSS.
/// </summary>
internal static class NotebookHtmlExporter
{
    private static readonly MarkdownPipeline MarkdigPipeline = new MarkdownPipelineBuilder()
        .UseAdvancedExtensions()
        .Build();

    private static readonly ICellRenderer FallbackRenderer = new ContentFallbackRenderer();

    /// <summary>
    /// Generates a complete, self-contained HTML document from the given notebook cells.
    /// </summary>
    public static byte[] Export(string? title, IReadOnlyList<CellModel> cells, ITheme? theme)
        => Export(title, cells, theme, options: null);

    /// <summary>
    /// Generates a complete, self-contained HTML document from the given notebook cells.
    /// When <paramref name="options"/> provides a layout ID, cells are filtered by visibility.
    /// </summary>
    public static byte[] Export(string? title, IReadOnlyList<CellModel> cells, ITheme? theme, ExportOptions? options)
    {
        var hasMermaid = false;
        var displayTitle = title ?? "Verso Notebook";
        var sb = new StringBuilder();

        var useVisibility = options?.LayoutId is not null
            && options.SupportedVisibilityStates is not null
            && options.Renderers is not null;
        var respectViewState = options?.RespectCellViewState ?? true;

        // Render cells into a temporary buffer so we know which features are used
        var bodySb = new StringBuilder();

        // Header
        bodySb.AppendLine("<div class=\"verso-export-header\">");
        bodySb.Append("<h1>").Append(WebUtility.HtmlEncode(displayTitle)).AppendLine("</h1>");
        bodySb.Append("<p class=\"verso-export-date\">Exported on ").Append(DateTime.UtcNow.ToString("yyyy-MM-dd")).AppendLine("</p>");
        bodySb.AppendLine("</div>");

        // Cells
        foreach (var cell in cells)
        {
            var layoutState = CellVisibilityState.Visible;
            if (useVisibility)
            {
                var renderer = options!.Renderers!.FirstOrDefault(r =>
                    string.Equals(r.CellTypeId, cell.Type, StringComparison.OrdinalIgnoreCase)) ?? FallbackRenderer;
                layoutState = CellVisibilityResolver.Resolve(cell, renderer, options.LayoutId!, options.SupportedVisibilityStates!);

                if (layoutState == CellVisibilityState.Hidden)
                    continue;

                if (layoutState == CellVisibilityState.Collapsed)
                {
                    RenderCollapsed(bodySb, cell);
                    continue;
                }
            }

            var outputVisibility = respectViewState
                ? CellViewStateReader.ReadOutputVisibility(cell)
                : CellViewStateMetadata.OutputExpanded;
            var inputCollapsed = respectViewState && CellViewStateReader.ReadInputCollapsed(cell);
            var outputPreviewLineCount = CellViewStateReader.ReadOutputPreviewLineCount(cell);

            var hideSource = layoutState == CellVisibilityState.OutputOnly || inputCollapsed;
            var hideOutputs = string.Equals(outputVisibility, CellViewStateMetadata.OutputHidden, StringComparison.Ordinal);
            var previewOutputs = string.Equals(outputVisibility, CellViewStateMetadata.OutputPreview, StringComparison.Ordinal);

            if (hideSource && (hideOutputs || cell.Outputs.Count == 0))
                continue;

            if (!hideSource)
            {
                if (string.Equals(cell.Type, "markdown", StringComparison.OrdinalIgnoreCase))
                {
                    RenderMarkdownCell(bodySb, cell);
                }
                else
                {
                    RenderCodeCellSource(bodySb, cell);
                }
            }

            if (!hideOutputs)
            {
                foreach (var output in cell.Outputs)
                {
                    RenderOutput(bodySb, output, previewOutputs, outputPreviewLineCount, ref hasMermaid);
                }
            }
        }

        // Footer
        bodySb.AppendLine("<div class=\"verso-export-footer\">");
        bodySb.AppendLine("<p>Generated by Verso</p>");
        bodySb.AppendLine("</div>");

        // Now build the final document with the correct head
        sb.AppendLine("<!DOCTYPE html>");
        sb.AppendLine("<html lang=\"en\">");

        // Head
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\" />");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />");
        sb.Append("<title>").Append(WebUtility.HtmlEncode(displayTitle)).AppendLine("</title>");
        sb.AppendLine("<style>");
        sb.Append(ThemeCssGenerator.BuildCss(theme));
        sb.Append(EmbeddedStylesheet);
        sb.AppendLine("</style>");
        if (hasMermaid)
        {
            sb.AppendLine("<script type=\"module\">");
            sb.AppendLine("import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs';");
            sb.AppendLine("mermaid.initialize({ startOnLoad: true });");
            sb.AppendLine("</script>");
        }
        sb.AppendLine("</head>");

        // Body
        sb.AppendLine("<body>");
        sb.AppendLine("<div class=\"verso-export\">");
        sb.Append(bodySb);
        sb.AppendLine("</div>"); // .verso-export
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return Encoding.UTF8.GetBytes(sb.ToString());
    }

    private static void RenderMarkdownCell(StringBuilder sb, CellModel cell)
    {
        if (string.IsNullOrEmpty(cell.Source)) return;

        sb.AppendLine("<div class=\"verso-output--html\">");
        sb.AppendLine(Markdown.ToHtml(cell.Source, MarkdigPipeline));
        sb.AppendLine("</div>");
    }

    private static void RenderCodeCellSource(StringBuilder sb, CellModel cell)
    {
        sb.AppendLine("<div class=\"verso-export-code\">");
        if (!string.IsNullOrEmpty(cell.Language))
        {
            sb.Append("<div class=\"verso-export-code-lang\">").Append(WebUtility.HtmlEncode(cell.Language)).AppendLine("</div>");
        }
        sb.AppendLine("<pre><code>");
        sb.Append(WebUtility.HtmlEncode(cell.Source));
        sb.AppendLine("</code></pre>");
        sb.AppendLine("</div>");
    }

    private static void RenderCollapsed(StringBuilder sb, CellModel cell)
    {
        var label = cell.Type ?? "cell";
        var title = !string.IsNullOrWhiteSpace(cell.Source)
            ? cell.Source.Split('\n')[0].TrimStart('#', ' ').Trim()
            : null;

        sb.AppendLine("<div class=\"verso-export-collapsed\">");
        sb.Append("<span class=\"verso-export-collapsed-type\">").Append(WebUtility.HtmlEncode(label)).Append("</span>");
        if (!string.IsNullOrEmpty(title))
        {
            sb.Append(" <span class=\"verso-export-collapsed-title\">").Append(WebUtility.HtmlEncode(title)).Append("</span>");
        }
        sb.AppendLine();
        sb.AppendLine("</div>");
    }

    private static void RenderOutput(StringBuilder sb, CellOutput output, bool previewText, int previewLineCount, ref bool hasMermaid)
    {
        if (output.IsError)
        {
            sb.AppendLine("<div class=\"verso-output--error\">");
            if (!string.IsNullOrEmpty(output.ErrorName))
            {
                sb.Append("<div class=\"verso-output--error-name\">").Append(WebUtility.HtmlEncode(output.ErrorName)).AppendLine("</div>");
            }
            sb.AppendLine("<pre>");
            sb.Append(WebUtility.HtmlEncode(output.Content));
            sb.AppendLine("</pre>");
            if (!string.IsNullOrEmpty(output.ErrorStackTrace))
            {
                sb.AppendLine("<pre class=\"verso-output--error-stack\">");
                sb.Append(WebUtility.HtmlEncode(output.ErrorStackTrace));
                sb.AppendLine("</pre>");
            }
            sb.AppendLine("</div>");
            return;
        }

        var mime = output.MimeType ?? "text/plain";

        switch (mime)
        {
            case "text/plain":
                sb.AppendLine("<div class=\"verso-output--text\">");
                sb.AppendLine("<pre>");
                WriteTruncated(sb, output.Content, previewText, previewLineCount);
                sb.AppendLine("</pre>");
                sb.AppendLine("</div>");
                break;

            case "text/html":
            case "image/svg+xml":
                sb.AppendLine("<div class=\"verso-output--html\">");
                sb.AppendLine(output.Content);
                sb.AppendLine("</div>");
                break;

            case "text/x-verso-mermaid":
                hasMermaid = true;
                sb.AppendLine("<div class=\"verso-output--html\">");
                sb.AppendLine("<pre class=\"mermaid\">");
                sb.Append(WebUtility.HtmlEncode(output.Content));
                sb.AppendLine("</pre>");
                sb.AppendLine("</div>");
                break;

            case "application/json":
                sb.AppendLine("<div class=\"verso-output--text\">");
                sb.AppendLine("<pre><code>");
                sb.Append(WebUtility.HtmlEncode(FormatJson(output.Content)));
                sb.AppendLine("</code></pre>");
                sb.AppendLine("</div>");
                break;

            case "text/csv":
                RenderCsvTable(sb, output.Content);
                break;

            default:
                if (mime.StartsWith("image/", StringComparison.Ordinal))
                {
                    sb.AppendLine("<div class=\"verso-output--html\">");
                    sb.Append("<img src=\"data:").Append(mime).Append(";base64,").Append(output.Content).AppendLine("\" />");
                    sb.AppendLine("</div>");
                }
                else
                {
                    sb.AppendLine("<div class=\"verso-output--text\">");
                    sb.AppendLine("<pre>");
                    WriteTruncated(sb, output.Content, previewText, previewLineCount);
                    sb.AppendLine("</pre>");
                    sb.AppendLine("</div>");
                }
                break;
        }
    }

    private static void WriteTruncated(StringBuilder sb, string content, bool previewText, int previewLineCount)
    {
        var lines = content.Split('\n');
        if (previewText && previewLineCount > 0 && lines.Length > previewLineCount)
        {
            for (int i = 0; i < previewLineCount; i++)
            {
                sb.AppendLine(WebUtility.HtmlEncode(lines[i]));
            }
            var omitted = lines.Length - previewLineCount;
            sb.Append("... (").Append(omitted).AppendLine(omitted == 1 ? " more line)" : " more lines)");
        }
        else
        {
            sb.Append(WebUtility.HtmlEncode(content));
        }
    }

    private static string FormatJson(string? json)
    {
        if (string.IsNullOrWhiteSpace(json)) return json ?? "";
        try
        {
            using var doc = System.Text.Json.JsonDocument.Parse(json);
            return System.Text.Json.JsonSerializer.Serialize(doc, new System.Text.Json.JsonSerializerOptions { WriteIndented = true });
        }
        catch
        {
            return json;
        }
    }

    private static void RenderCsvTable(StringBuilder sb, string? csv)
    {
        if (string.IsNullOrWhiteSpace(csv))
        {
            sb.AppendLine("<div class=\"verso-output--text\"><pre></pre></div>");
            return;
        }

        sb.AppendLine("<div class=\"verso-output--html\">");
        sb.AppendLine("<table>");

        var lines = csv.Split('\n');
        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i].TrimEnd('\r');
            if (string.IsNullOrEmpty(line)) continue;

            var cells = ParseCsvLine(line);
            var tag = i == 0 ? "th" : "td";

            if (i == 0) sb.AppendLine("<thead>");
            if (i == 1) sb.AppendLine("<tbody>");

            sb.Append("<tr>");
            foreach (var cell in cells)
            {
                sb.Append('<').Append(tag).Append('>');
                sb.Append(WebUtility.HtmlEncode(cell));
                sb.Append("</").Append(tag).Append('>');
            }
            sb.AppendLine("</tr>");

            if (i == 0) sb.AppendLine("</thead>");
        }

        if (lines.Length > 1) sb.AppendLine("</tbody>");
        sb.AppendLine("</table>");
        sb.AppendLine("</div>");
    }

    private static List<string> ParseCsvLine(string line)
    {
        var fields = new List<string>();
        var current = new StringBuilder();
        var inQuotes = false;

        for (var i = 0; i < line.Length; i++)
        {
            var ch = line[i];
            if (inQuotes)
            {
                if (ch == '"' && i + 1 < line.Length && line[i + 1] == '"')
                {
                    current.Append('"');
                    i++;
                }
                else if (ch == '"')
                {
                    inQuotes = false;
                }
                else
                {
                    current.Append(ch);
                }
            }
            else if (ch == '"')
            {
                inQuotes = true;
            }
            else if (ch == ',')
            {
                fields.Add(current.ToString());
                current.Clear();
            }
            else
            {
                current.Append(ch);
            }
        }

        fields.Add(current.ToString());
        return fields;
    }

    private const string EmbeddedStylesheet = @"
/* Export layout */
body {
  margin: 0;
  padding: 0;
  background: var(--verso-editor-background, #ffffff);
  color: var(--verso-editor-foreground, #1e1e1e);
  font-family: var(--verso-ui-font-family, 'Segoe UI', sans-serif);
  font-size: var(--verso-ui-font-size, 13px);
  line-height: var(--verso-ui-font-line-height, 1.4);
}

.verso-export {
  max-width: 900px;
  margin: 0 auto;
  padding: 2rem 1.5rem;
}

.verso-export-header {
  margin-bottom: 2rem;
  padding-bottom: 1rem;
  border-bottom: 1px solid var(--verso-border-default, #e0e0e0);
}

.verso-export-header h1 {
  margin: 0 0 0.25rem 0;
  font-family: var(--verso-h1-font-family, 'Segoe UI', sans-serif);
  font-size: var(--verso-h1-font-size, 32px);
  font-weight: var(--verso-h1-font-weight, 700);
}

.verso-export-date {
  margin: 0;
  color: var(--verso-editor-line-number, #858585);
  font-size: 0.85em;
}

.verso-export-footer {
  margin-top: 2rem;
  padding-top: 1rem;
  border-top: 1px solid var(--verso-border-default, #e0e0e0);
  color: var(--verso-editor-line-number, #858585);
  font-size: 0.85em;
  text-align: center;
}

/* Code blocks */
.verso-export-code {
  margin: 1rem 0;
  background: var(--verso-cell-background, #f5f5f5);
  border: 1px solid var(--verso-cell-border, #e0e0e0);
  border-radius: var(--verso-cell-border-radius, 4px);
  overflow: hidden;
}

.verso-export-code-lang {
  padding: 0.25rem 0.75rem;
  background: var(--verso-toolbar-background, #f0f0f0);
  color: var(--verso-editor-line-number, #858585);
  font-size: 0.75em;
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.verso-export-code pre {
  margin: 0;
  padding: var(--verso-cell-padding, 12px);
  overflow-x: auto;
}

.verso-export-code code {
  font-family: var(--verso-editor-font-family, 'Cascadia Code', monospace);
  font-size: var(--verso-editor-font-size, 14px);
  line-height: var(--verso-editor-font-line-height, 1.4);
}

/* Output blocks */
.verso-output--text {
  margin: 0.5rem 0 1rem 0;
  padding: var(--verso-output-padding, 8px);
  background: var(--verso-cell-output-background, #fafafa);
  color: var(--verso-cell-output-foreground, #1e1e1e);
  border-left: 3px solid var(--verso-accent-primary, #0078d4);
}

.verso-output--text pre {
  margin: 0;
  white-space: pre-wrap;
  word-wrap: break-word;
  font-family: var(--verso-code-output-font-family, 'Cascadia Mono', monospace);
  font-size: var(--verso-code-output-font-size, 13px);
}

.verso-output--html {
  margin: 1rem 0;
  font-family: var(--verso-prose-font-family, 'Georgia', serif);
  font-size: var(--verso-prose-font-size, 16px);
  line-height: var(--verso-prose-font-line-height, 1.6);
}

.verso-output--html h1 { font-family: var(--verso-h1-font-family, 'Segoe UI', sans-serif); font-size: var(--verso-h1-font-size, 32px); font-weight: var(--verso-h1-font-weight, 700); }
.verso-output--html h2 { font-family: var(--verso-h2-font-family, 'Segoe UI', sans-serif); font-size: var(--verso-h2-font-size, 26px); font-weight: var(--verso-h2-font-weight, 700); }
.verso-output--html h3 { font-family: var(--verso-h3-font-family, 'Segoe UI', sans-serif); font-size: var(--verso-h3-font-size, 22px); font-weight: var(--verso-h3-font-weight, 600); }
.verso-output--html h4 { font-family: var(--verso-h4-font-family, 'Segoe UI', sans-serif); font-size: var(--verso-h4-font-size, 18px); font-weight: var(--verso-h4-font-weight, 600); }
.verso-output--html h5 { font-family: var(--verso-h5-font-family, 'Segoe UI', sans-serif); font-size: var(--verso-h5-font-size, 15px); font-weight: var(--verso-h5-font-weight, 600); }
.verso-output--html h6 { font-family: var(--verso-h6-font-family, 'Segoe UI', sans-serif); font-size: var(--verso-h6-font-size, 13px); font-weight: var(--verso-h6-font-weight, 600); }

.verso-output--html pre,
.verso-output--html code {
  font-family: var(--verso-editor-font-family, 'Cascadia Code', monospace);
  font-size: 0.9em;
}

.verso-output--html pre {
  background: var(--verso-cell-background, #f5f5f5);
  padding: 0.75rem;
  border-radius: 4px;
  overflow-x: auto;
}

.verso-output--html table {
  border-collapse: collapse;
  margin: 1rem 0;
}

.verso-output--html th,
.verso-output--html td {
  border: 1px solid var(--verso-border-default, #e0e0e0);
  padding: 0.4rem 0.75rem;
}

.verso-output--html th {
  background: var(--verso-toolbar-background, #f0f0f0);
}

.verso-output--html img {
  max-width: 100%;
}

/* Error output */
.verso-output--error {
  margin: 0.5rem 0 1rem 0;
  padding: var(--verso-output-padding, 8px);
  background: var(--verso-cell-error-background, #fde7e9);
  color: var(--verso-cell-error-foreground, #a1260d);
  border-left: 3px solid var(--verso-status-error, #e51400);
  border-radius: 0 var(--verso-cell-border-radius, 4px) var(--verso-cell-border-radius, 4px) 0;
}

.verso-output--error-name {
  font-weight: 700;
  margin-bottom: 0.25rem;
}

.verso-output--error pre {
  margin: 0;
  white-space: pre-wrap;
  word-wrap: break-word;
  font-family: var(--verso-code-output-font-family, 'Cascadia Mono', monospace);
  font-size: var(--verso-code-output-font-size, 13px);
}

.verso-output--error-stack {
  margin-top: 0.5rem !important;
  opacity: 0.8;
  font-size: 0.85em;
}

/* Print styles */
@media print {
  body { background: white; }
  .verso-export { max-width: none; padding: 0; }
  .verso-export-code { break-inside: avoid; }
  .verso-output--error { break-inside: avoid; }
}
";
}
